### ISSUE TITLE
How about Github / Github Enterprise

### ISSUE THREAD

**Issue by tangentlin** [minhdam/BitbucketDiffTree#17]
I definitely love the DiffTree, and I wonder if there is any plan of adopting this for GitHub / GitHub Enterprise.

**Comment by minhdam** [comment]
@tangentlin Sorry, I do not really understand your question. I just wanted to build the DiffTree for free use.

**Comment by tangentlin** [comment]
Sorry about the confusion @minhdam , I would like to see if DiffTree can also reformat Github/Github Enterprise pull requests the same way it does for Bitbucket.

**Comment by minhdam** [comment]
@tangentlin You can try this chrome extension for Github/Github Enterprise:
https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US

Hope that helps.
