### ISSUE TITLE
Chrome extension page returns 404 - is this repo being maintained anymore?

### ISSUE THREAD

**Issue by anupshah** [minhdam/BitbucketDiffTree#19]
Hi,

A colleague was trying to install this extension on a new machine of theirs.

The URL provided here results in a 404, and a search on the chrome extension store does not find it.

Has it been removed?

Thanks!

**Comment by minhdam** [comment]
Hi,

I'm so sorry Anup. The extension has been removed recently by Google. I will contact Google to resolve the issue, and will notify you once the extension will be up again.

Thank you!

**Comment by anupshah** [comment]
Many thanks!

**Comment by minhdam** [comment]
Hi @anupshah,

Sorry for the late response. The extension is now up again.

Please let me know if you have any problems.

Cheers!

**Comment by anupshah** [comment]
Hi, sorry for my own slow reply too

Many thanks for resolving this.
