### ISSUE TITLE
Clicking on the PR comment count badge in bottom corner does not switch to the file

### ISSUE THREAD

**Issue by anupshah** [minhdam/BitbucketDiffTree#3]
First off this is an awesome tool. Many thanks!

An issue I noticed is that while looking at a PR, when a comment comes in, the badge with the counter in the bottom left shows up (as before) but this time when you click it to go to that comment (in another file) it just scrolls up – the counter decreases but the new file is not shown. This makes it hard to jump between files.

**Comment by minhdam** [comment]
Hi Anup,

The issue has partially fixed in v1.4.7. Please see if it works for you.

One remaining issue is that if the file is collapsed, when clicking on comment badge, it cannot open the parent folder to show that file. I'm going to fix it soon.

Cheers.

**Comment by anupshah** [comment]
Hi, it is working well enough for me at the moment. Will open another issue if I spot anything further. Many thanks.
