### ISSUE TITLE
[Feature request] Better support for rebase-based PRs 

### ISSUE THREAD

**Issue by DethAriel** [minhdam/BitbucketDiffTree#7]
Hello! To start with, great work on the extension, I love it! The moment file check marks have been introduced, it has become even more valuable!

But my team uses git rebase to tackle review comments. So, whenever someone makes a little change to the review, it's hard to spot, since all the files already have checkmarks on them. Maybe there is a way the extension would track file contents somehow? E.g. a substring of an md5 hash of all the file changes at the time the "check" mark is placed?

I'd be happy to help you out on this front, would you be willing to accept a PR for this?

Again, thanks a lot for all you do!

**Comment by minhdam** [comment]
Hi Deth,

Thanks for using the extension and providing the good suggestion on tracking the file changes. 

I'm very happy if you can create a PR for this feature.

Cheers.

**Comment by DethAriel** [comment]
@minhdam that sounds awesome! I'll be working on that then for the next couple of days, and submit a PR once I have something
